#
# Copyright (c) 2022-2023 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
springdoc.api-docs.enabled=false
springdoc.pathsToMatch=/v1/**,/session/**,/dashboard/**,/system/**,/user/**
springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

higress-console.build.version=@app.build.version@
higress-console.build.dev=@app.build.dev@

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
server.compression.min-response-size=2048
server.compression.excluded-user-agents=MSIE 6.0,UCBrowser

# Add %mdc (Mapped Diagnostic Context) based on the Spring Boot default logging pattern found in org.springframework.boot.logging.logback.DefaultLogbackConfiguration
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(70396){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} {%mdc} %clr(:){faint} %m%n%wEx


# Backend configuration for connecting to higress-for-wgb-uat namespace

# Kubeconfig path
higress-console.kube-config=/Users/zengyr7/Downloads/cls-en1

# Controller namespace (where Higress controller is deployed)
higress-console.ns=higress-for-wgb-uat

# Watched namespace (the namespace to manage)
higress-console.controller.watched-namespace=higress-for-wgb-uat

# Controller service configuration
higress-console.controller.service.name=a42a408ba116a44d1-higress-controller
#higress-console.controller.service.host=11.67.151.58
higress-console.controller.service.host=higress-controller.higress-for-wgb-uat.svc.cluster.local
higress-console.controller.service.port=15014

higress-console.controller.ingress-class-name=a42a408ba116a44d1-higress

# JWT policy
higress-console.controller.jwt-policy=THIRD_PARTY_JWT

higress-console.controller.access-token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImtLTFBGMmk0LWFBVEFVdU9nR2h3YTZfNFpNYmxaMEU1Mi1PUDYybDhyTmMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoaWdyZXNzLWZvci13Z2ItdWF0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImE0MmE0MDhiYTExNmE0NGQxLWhpZ3Jlc3MtY29udHJvbGxlci10b2tlbi16YnA0eCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhNDJhNDA4YmExMTZhNDRkMS1oaWdyZXNzLWNvbnRyb2xsZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI3M2I0NDgzNi0yZTU1LTQ3MDAtOWE3My1iY2VhZjVlOGE5YzAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aGlncmVzcy1mb3Itd2diLXVhdDphNDJhNDA4YmExMTZhNDRkMS1oaWdyZXNzLWNvbnRyb2xsZXIifQ.AOEsBfL0RwnIEj0TUfaPZYX29-Vbl3tLHMu3aes1TFytnW8Go54SZBHtpnI9cbAZZb_eP_N-PkbQq4nhGaFfuZR_ouVveQFl4Q-MdwS1C0YUqPGYLC7EF222_hkQV01yLOl4UKdNhLfxAz5e3kTVHY70HIEa5DmKJoIQDVixNw-c6VoF9fW5j_8ZDOphmXY59CbReUZy8qnnP1ykOy_QZP3KPoIgHNrRFJDo8O3g9_N9JOZbMxkHY3Zi-lGtNJCYoK8EQTyfPwa4vuI_FM9Cel2L_JCb-rC0pkPlqlxzI80IjlKLTAoEXYQbu78nqNPsx3GAnR-dr7jlb6ZC8bm93A

# Cluster domain suffix
CLUSTER_DOMAIN_SUFFIX=cluster.local
